apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: {{ .Release.Namespace }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: "{{ .Values.backendImage.repository }}:{{ .Values.backendImage.tag }}"
          imagePullPolicy: {{ .Values.backendImage.pullPolicy }}
          ports:
            - containerPort: 80
          env:
            - name: DOMAIN
              value: {{ .Values.environment.domain | quote }}
            - name: ENVIRONMENT
              value: {{ .Values.environment.environment | quote }}
            - name: PROJECT_NAME
              value: {{ .Values.environment.projectName | quote }}
            - name: STACK_NAME
              value: {{ .Values.environment.stackName | quote }}
            - name: BACKEND_CORS_ORIGINS  
              value: {{ .Values.environment.backend.backendCorsOrigins | quote }}
            - name: FIRST_SUPERUSER 
              value: {{ .Values.environment.backend.firstSuperuser | quote }}
            - name: USERS_OPEN_REGISTRATION 
              value: {{ .Values.environment.backend.usersOpenRegistration | quote }}
            - name: SMTP_HOST 
              value: {{ .Values.environment.emails.smtpHost | quote }}
            - name: SMTP_USER 
              value: {{ .Values.environment.emails.smtpUser | quote }}
            - name: EMAILS_FROM_EMAIL 
              value: {{ .Values.environment.emails.emailsFromEmail | quote }}
            - name: SMTP_TLS  
              value: {{ .Values.environment.emails.smtpTls | quote }}
            - name: SMTP_SSL  
              value: {{ .Values.environment.emails.smtpSsl | quote }}
            - name: SMTP_PORT 
              value: {{ .Values.environment.emails.smtpPort | quote }}
            - name: POSTGRES_SERVER 
              value: {{ .Values.postgresql.postgresServer | quote }}
            - name: POSTGRES_PORT 
              value: {{ .Values.postgresql.postgresPort | quote }}
            - name: PGDATA  
              value: {{ .Values.postgresql.pgdata | quote }}
            - name: POSTGRES_USER 
              value: {{ .Values.postgresql.postgresUser | quote }}
            - name: POSTGRES_DB 
              value: {{ .Values.postgresql.postgresDb | quote }}
            - name: SENTRY_DSN  
              value: {{ .Values.environment.sentryDsn | quote }}
            - name: VITE_API_URL  
              value: {{ .Values.environment.viteApiUrl | quote }}
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "photo-monitor-dev.fullname" . }}-secrets
                  key: POSTGRES_PASSWORD
            - name: FIRST_SUPERUSER_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "photo-monitor-dev.fullname" . }}-secrets
                  key: FIRST_SUPERUSER_PASSWORD
        - name: postgres
          image: "{{ .Values.postgresql.image.repository }}:{{ .Values.postgresql.image.tag }}"
          imagePullPolicy: {{ .Values.postgresql.image.pullPolicy }}
          env:
            - name: POSTGRES_DB
              value: {{ .Values.postgresql.postgresDb | quote }}
            - name: POSTGRES_USER
              value: {{ .Values.postgresql.postgresUser | quote }}
            - name: PGDATA
              value: {{ .Values.postgresql.pgdata | quote}}
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "photo-monitor-dev.fullname" . }}-secrets
                  key: POSTGRES_PASSWORD
          ports:
            - containerPort: {{ .Values.postgresql.service.port  }}
          volumeMounts:
            - mountPath: /postgres/
              name: postgres-storage 
      imagePullSecrets:
        - name: {{ .Values.imagePullSecrets }}
      volumes:
        - name: postgres-storage
          persistentVolumeClaim:
            claimName: {{ include "photo-monitor-dev.fullname" . }}-postgresql-pvc