# (C) Copyright 2024 rustyweise.com
---
apiVersion: v1
kind: Secret
metadata:
  name: docker-registry-secret
  namespace: { { .Release.Namespace } }
  labels:
    app: { { .Release.Namespace } }
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: { { template "imagePullSecret" . } }
