apiVersion: v1
kind: Service
metadata:
  name: {{ include "photo-monitor-dev.fullname" . }}-postgresql-svc
  namespace: {{ .Release.Namespace }}
spec:
  type: {{ .Values.postgresql.service.type }}
  ports:
    - port: {{ .Values.postgresql.service.port }}
      targetPort: {{ .Values.postgresql.service.port }}
      protocol: TCP
  selector: {{- include "photo-monitor-dev.labels" . | nindent 4 }}
