apiVersion: v1
kind: Secret
metadata:
  name: {{ include "photo-monitor-dev.fullname" . }}-secrets
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  POSTGRES_PASSWORD: {{ .Values.postgresql.postgresPassword | b64enc }}
  SECRET_KEY: {{ .Values.environment.backend.secretKey | b64enc }}
  SMTP_PASSWORD: {{ .Values.environment.emails.smtpPassword | b64enc }}
  FIRST_SUPERUSER_PASSWORD: {{ .Values.environment.backend.firstSuperuserPassword | b64enc }}
